# Notre workflow CI CD pour le push de tag sur main et les PR

name: CI

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean compile 
      - uses: actions/upload-artifact@v2
        with:
          name: menu-client.jar
          path: ./target/menu-client.jar
          
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean verify
      
  release:
    needs: [build, tests]
    runs-on: ubuntu-20.04
    if: github.repository == 'JulesPierrat/menus-cli' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/dowload-artifact@v2
        with:
          name: menu-cli.jar
          path: ./target/menu-cli.jar
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/menu-cli.jar
          asset_name: menu-cli.jar
          asset_content_type: application/jar
